# Nixpacks configuration for Medusa

[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.install]
cmds = ["cd dohhh && yarn install"]

[phases.build]
cmds = ["cd dohhh && yarn build"]

[start]
cmd = "cd dohhh && NODE_OPTIONS='--dns-result-order=ipv4first' yarn start:railway"

[variables]
NODE_ENV = "production"
PORT = "9000"
NODE_OPTIONS = "--dns-result-order=ipv4first"